apiVersion: batch/v1
kind: CronJob
metadata:
  name: msynbot.delsitelinks
  labels:
    name: msynbot.delsitelinks
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "42 10 * * 2"
# successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: delsitelinks
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            resources:
              requests:
                memory: "6Gi"
                cpu: "1000m"
              limits:
                memory: "8Gi"
                cpu: "1000m"
            env:
            - name: PYTHONPATH
              value: /data/project/shared/pywikibot/stable
            - name: HOME
              value: /data/project/msynbot
            workingDir: /data/project/msynbot/pywikibot_tasks/inexistent_sitelinks
            command: [ venv/bin/python3 ]
            args: [ main.py ]
          restartPolicy: OnFailure
